// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaLBM_LtOzMND9X0TPMZh9dSWW-KASpAw',
    appId: '1:473344588416:web:f84ab00c7a7db1f8c60465',
    messagingSenderId: '473344588416',
    projectId: 'notes-48b92',
    authDomain: 'notes-48b92.firebaseapp.com',
    databaseURL: 'https://notes-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'notes-48b92.appspot.com',
    measurementId: 'G-DMHHN8FEYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHTN7G70tskY7GYU8-4FmO7Z_INdArIs',
    appId: '1:473344588416:android:342e0606d82bf251c60465',
    messagingSenderId: '473344588416',
    projectId: 'notes-48b92',
    databaseURL: 'https://notes-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'notes-48b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjzRS8lMCYif4un2KxxpDaH_lz--kJ4U',
    appId: '1:473344588416:ios:a191d618a0d902fac60465',
    messagingSenderId: '473344588416',
    projectId: 'notes-48b92',
    databaseURL: 'https://notes-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'notes-48b92.appspot.com',
    iosBundleId: 'com.example.remote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjzRS8lMCYif4un2KxxpDaH_lz--kJ4U',
    appId: '1:473344588416:ios:6a60fbe219fdcbccc60465',
    messagingSenderId: '473344588416',
    projectId: 'notes-48b92',
    databaseURL: 'https://notes-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'notes-48b92.appspot.com',
    iosBundleId: 'com.example.remote.RunnerTests',
  );
}
